//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.Mvc.Resources.MvcResources", typeof(MvcResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The current request for action &apos;{0}&apos; on controller type &apos;{1}&apos; is ambiguous between the following action methods:{2} 的本地化字符串。
        /// </summary>
        internal static string ActionMethodSelector_AmbiguousMatch {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} on type {1} 的本地化字符串。
        /// </summary>
        internal static string ActionMethodSelector_AmbiguousMatchType {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A required anti-forgery token was not supplied or was invalid. 的本地化字符串。
        /// </summary>
        internal static string AntiForgeryToken_ValidationFailed {
            get {
                return ResourceManager.GetString("AntiForgeryToken_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lookup for method &apos;{0}&apos; on controller type &apos;{1}&apos; failed because of an ambiguity between the following methods:{2} 的本地化字符串。
        /// </summary>
        internal static string AsyncActionMethodSelector_AmbiguousMethodMatch {
            get {
                return ResourceManager.GetString("AsyncActionMethodSelector_AmbiguousMethodMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not locate a method named &apos;{0}&apos; on controller type {1}. 的本地化字符串。
        /// </summary>
        internal static string AsyncActionMethodSelector_CouldNotFindMethod {
            get {
                return ResourceManager.GetString("AsyncActionMethodSelector_CouldNotFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided IAsyncResult has already been consumed. 的本地化字符串。
        /// </summary>
        internal static string AsyncCommon_AsyncResultAlreadyConsumed {
            get {
                return ResourceManager.GetString("AsyncCommon_AsyncResultAlreadyConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller of type &apos;{0}&apos; must subclass AsyncController or implement the IAsyncManagerContainer interface. 的本地化字符串。
        /// </summary>
        internal static string AsyncCommon_ControllerMustImplementIAsyncManagerContainer {
            get {
                return ResourceManager.GetString("AsyncCommon_ControllerMustImplementIAsyncManagerContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided IAsyncResult is not valid for this method. 的本地化字符串。
        /// </summary>
        internal static string AsyncCommon_InvalidAsyncResult {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The timeout value must be non-negative or Timeout.Infinite. 的本地化字符串。
        /// </summary>
        internal static string AsyncCommon_InvalidTimeout {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The action &apos;{0}&apos; is accessible only by a child request. 的本地化字符串。
        /// </summary>
        internal static string ChildActionOnlyAttribute_MustBeInChildRequest {
            get {
                return ResourceManager.GetString("ChildActionOnlyAttribute_MustBeInChildRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be a number. 的本地化字符串。
        /// </summary>
        internal static string ClientDataTypeModelValidatorProvider_FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No route in the route table matches the supplied values. 的本地化字符串。
        /// </summary>
        internal static string Common_NoRouteMatched {
            get {
                return ResourceManager.GetString("Common_NoRouteMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The partial view &apos;{0}&apos; was not found. The following locations were searched:{1} 的本地化字符串。
        /// </summary>
        internal static string Common_PartialViewNotFound {
            get {
                return ResourceManager.GetString("Common_PartialViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property &apos;{0}&apos; cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string Common_PropertyCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Common_PropertyCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0}.{1} could not be found. 的本地化字符串。
        /// </summary>
        internal static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        internal static string Common_TriState_False {
            get {
                return ResourceManager.GetString("Common_TriState_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Set 的本地化字符串。
        /// </summary>
        internal static string Common_TriState_NotSet {
            get {
                return ResourceManager.GetString("Common_TriState_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        internal static string Common_TriState_True {
            get {
                return ResourceManager.GetString("Common_TriState_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} must derive from {1} 的本地化字符串。
        /// </summary>
        internal static string Common_TypeMustDriveFromType {
            get {
                return ResourceManager.GetString("Common_TypeMustDriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is invalid. 的本地化字符串。
        /// </summary>
        internal static string Common_ValueNotValidForProperty {
            get {
                return ResourceManager.GetString("Common_ValueNotValidForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The view &apos;{0}&apos; or its master was not found. The following locations were searched:{1} 的本地化字符串。
        /// </summary>
        internal static string Common_ViewNotFound {
            get {
                return ResourceManager.GetString("Common_ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A public action method &apos;{0}&apos; was not found on controller &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Controller_UnknownAction {
            get {
                return ResourceManager.GetString("Controller_UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model of type &apos;{0}&apos; could not be updated. 的本地化字符串。
        /// </summary>
        internal static string Controller_UpdateModel_UpdateUnsuccessful {
            get {
                return ResourceManager.GetString("Controller_UpdateModel_UpdateUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model of type &apos;{0}&apos; is not valid. 的本地化字符串。
        /// </summary>
        internal static string Controller_Validate_ValidationFailed {
            get {
                return ResourceManager.GetString("Controller_Validate_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A single instance of controller &apos;{0}&apos; cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request. 的本地化字符串。
        /// </summary>
        internal static string ControllerBase_CannotHandleMultipleRequests {
            get {
                return ResourceManager.GetString("ControllerBase_CannotHandleMultipleRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred when trying to create the IControllerFactory &apos;{0}&apos;. Make sure that the controller factory has a public parameterless constructor. 的本地化字符串。
        /// </summary>
        internal static string ControllerBuilder_ErrorCreatingControllerFactory {
            get {
                return ResourceManager.GetString("ControllerBuilder_ErrorCreatingControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IControllerFactory &apos;{0}&apos; did not return a controller for the name &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ControllerBuilder_FactoryReturnedNull {
            get {
                return ResourceManager.GetString("ControllerBuilder_FactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller factory type &apos;{0}&apos; must implement the IControllerFactory interface. 的本地化字符串。
        /// </summary>
        internal static string ControllerBuilder_MissingIControllerFactory {
            get {
                return ResourceManager.GetString("ControllerBuilder_MissingIControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has a DisplayColumn attribute for {1}, but property {1} does not exist. 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelMetadataProvider_UnknownProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has a DisplayColumn attribute for {1}, but property {1} does not have a public getter. 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelMetadataProvider_UnreadableProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnreadableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} must have a public constructor which accepts three parameters of types {1}, {2}, and {3} 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelValidatorProvider_ConstructorRequirements {
            get {
                return ResourceManager.GetString("DataAnnotationsModelValidatorProvider_ConstructorRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{1} 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_ControllerNameAmbiguous_WithoutRouteUrl {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ControllerNameAmbiguous_WithoutRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request (&apos;{1}&apos;) does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{2} 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_ControllerNameAmbiguous_WithRouteUrl {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ControllerNameAmbiguous_WithRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred when trying to create a controller of type &apos;{0}&apos;. Make sure that the controller has a parameterless public constructor. 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_ErrorCreatingController {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ErrorCreatingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller for path &apos;{0}&apos; was not found or does not implement IController. 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_NoControllerFound {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_NoControllerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller type &apos;{0}&apos; must implement IController. 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_TypeDoesNotSubclassControllerBase {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_TypeDoesNotSubclassControllerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is not valid for {1}. 的本地化字符串。
        /// </summary>
        internal static string DefaultModelBinder_ValueInvalid {
            get {
                return ResourceManager.GetString("DefaultModelBinder_ValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value is required. 的本地化字符串。
        /// </summary>
        internal static string DefaultModelBinder_ValueRequired {
            get {
                return ResourceManager.GetString("DefaultModelBinder_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of ticks for the TimeSpan value must be greater than or equal to 0. 的本地化字符串。
        /// </summary>
        internal static string DefaultViewLocationCache_NegativeTimeSpan {
            get {
                return ResourceManager.GetString("DefaultViewLocationCache_NegativeTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not inherit from Exception. 的本地化字符串。
        /// </summary>
        internal static string ExceptionViewAttribute_NonExceptionType {
            get {
                return ResourceManager.GetString("ExceptionViewAttribute_NonExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expression compiler was unable to evaluate the indexer expression &apos;{0}&apos; because it references the model parameter &apos;{1}&apos; which is unavailable. 的本地化字符串。
        /// </summary>
        internal static string ExpressionHelper_InvalidIndexerExpression {
            get {
                return ResourceManager.GetString("ExpressionHelper_InvalidIndexerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order must be greater than or equal to -1. 的本地化字符串。
        /// </summary>
        internal static string FilterAttribute_OrderOutOfRange {
            get {
                return ResourceManager.GetString("FilterAttribute_OrderOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The GET and POST HTTP methods are not supported. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_InvalidHttpMethod {
            get {
                return ResourceManager.GetString("HtmlHelper_InvalidHttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified HttpVerbs value is not supported. The supported values are Delete, Head, and Put. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_InvalidHttpVerb {
            get {
                return ResourceManager.GetString("HtmlHelper_InvalidHttpVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no ViewData item of type &apos;{1}&apos; that has the key &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_MissingSelectData {
            get {
                return ResourceManager.GetString("HtmlHelper_MissingSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_TextAreaParameterOutOfRange {
            get {
                return ResourceManager.GetString("HtmlHelper_TextAreaParameterOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ViewData item that has the key &apos;{0}&apos; is of type &apos;{1}&apos; but must be of type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_WrongSelectDataType {
            get {
                return ResourceManager.GetString("HtmlHelper_WrongSelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This request has been blocked because sensitive information could be disclosed to third party web sites when this is used in a GET request. To allow GET requests, set JsonRequestBehavior to AllowGet. 的本地化字符串。
        /// </summary>
        internal static string JsonRequest_GetNotAllowed {
            get {
                return ResourceManager.GetString("JsonRequest_GetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred when trying to create the IModelBinder &apos;{0}&apos;. Make sure that the binder has a public parameterless constructor. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderAttribute_ErrorCreatingModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderAttribute_ErrorCreatingModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not implement the IModelBinder interface. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderAttribute_TypeNotIModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderAttribute_TypeNotIModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; contains multiple attributes that inherit from CustomModelBinderAttribute. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderDictionary_MultipleAttributes {
            get {
                return ResourceManager.GetString("ModelBinderDictionary_MultipleAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This property setter is obsolete, because its value is derived from ModelMetadata.Model now. 的本地化字符串。
        /// </summary>
        internal static string ModelMetadata_PropertyNotSettable {
            get {
                return ResourceManager.GetString("ModelMetadata_PropertyNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The associated metadata type for type &apos;{0}&apos; contains the following unknown properties or fields: {1}. Please make sure that the names of these members match the names of the properties on the main type. 的本地化字符串。
        /// </summary>
        internal static string PrivateAssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("PrivateAssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Child actions are not allowed to perform redirect actions. 的本地化字符串。
        /// </summary>
        internal static string RedirectAction_CannotRedirectInChildAction {
            get {
                return ResourceManager.GetString("RedirectAction_CannotRedirectInChildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create a descriptor for instance method &apos;{0}&apos; on type &apos;{1}&apos; because the type does not derive from ControllerBase. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_CannotCallInstanceMethodOnNonControllerType {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallInstanceMethodOnNonControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot call action method &apos;{0}&apos; on controller &apos;{1}&apos; because the parameter &apos;{2}&apos; is passed by reference. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_CannotCallMethodsWithOutOrRefParameters {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallMethodsWithOutOrRefParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot call action method &apos;{0}&apos; on controller &apos;{1}&apos; because the action method is a generic method. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_CannotCallOpenGenericMethods {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallOpenGenericMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameters dictionary contains a null entry for parameter &apos;{0}&apos; of non-nullable type &apos;{1}&apos; for method &apos;{2}&apos; in &apos;{3}&apos;. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameters dictionary does not contain an entry for parameter &apos;{0}&apos; of type &apos;{1}&apos; for method &apos;{2}&apos; in &apos;{3}&apos;. The dictionary must contain an entry for each parameter, including parameters that have null values. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_ParameterNotInDictionary {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterNotInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameters dictionary contains an invalid entry for parameter &apos;{0}&apos; for method &apos;{1}&apos; in &apos;{2}&apos;. The dictionary contains a value of type &apos;{3}&apos;, but the parameter requires a value of type &apos;{4}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_ParameterValueHasWrongType {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterValueHasWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The asynchronous action method &apos;{0}&apos; cannot be executed synchronously. 的本地化字符串。
        /// </summary>
        internal static string ReflectedAsyncActionDescriptor_CannotExecuteSynchronously {
            get {
                return ResourceManager.GetString("ReflectedAsyncActionDescriptor_CannotExecuteSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; on method &apos;{1}&apos; contains multiple attributes that inherit from CustomModelBinderAttribute. 的本地化字符串。
        /// </summary>
        internal static string ReflectedParameterBindingInfo_MultipleConverterAttributes {
            get {
                return ResourceManager.GetString("ReflectedParameterBindingInfo_MultipleConverterAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested resource can only be accessed via SSL. 的本地化字符串。
        /// </summary>
        internal static string RequireHttpsAttribute_MustUseSsl {
            get {
                return ResourceManager.GetString("RequireHttpsAttribute_MustUseSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The SessionStateTempDataProvider class requires session state to be enabled. 的本地化字符串。
        /// </summary>
        internal static string SessionStateTempDataProvider_SessionStateDisabled {
            get {
                return ResourceManager.GetString("SessionStateTempDataProvider_SessionStateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An operation that crossed a synchronization context failed. See the inner exception for more information. 的本地化字符串。
        /// </summary>
        internal static string SynchronizationContextUtil_ExceptionThrown {
            get {
                return ResourceManager.GetString("SynchronizationContextUtil_ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to locate an appropriate template for type {0}. 的本地化字符串。
        /// </summary>
        internal static string TemplateHelpers_NoTemplate {
            get {
                return ResourceManager.GetString("TemplateHelpers_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Templates can be used only with field access, property access, single-dimension array index, or single-parameter custom indexer expressions. 的本地化字符串。
        /// </summary>
        internal static string TemplateHelpers_TemplateLimitations {
            get {
                return ResourceManager.GetString("TemplateHelpers_TemplateLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Collection template was used with an object of type &apos;{0}&apos;, which does not implement System.IEnumerable. 的本地化字符串。
        /// </summary>
        internal static string Templates_TypeMustImplementIEnumerable {
            get {
                return ResourceManager.GetString("Templates_TypeMustImplementIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file is automatically generated. Please do not modify the contents of this file. 的本地化字符串。
        /// </summary>
        internal static string TypeCache_DoNotModify {
            get {
                return ResourceManager.GetString("TypeCache_DoNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter conversion from type &apos;{0}&apos; to type &apos;{1}&apos; failed. See the inner exception for more information. 的本地化字符串。
        /// </summary>
        internal static string ValueProviderResult_ConversionThrew {
            get {
                return ResourceManager.GetString("ValueProviderResult_ConversionThrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter conversion from type &apos;{0}&apos; to type &apos;{1}&apos; failed because no type converter can convert between these types. 的本地化字符串。
        /// </summary>
        internal static string ValueProviderResult_NoConverterExists {
            get {
                return ResourceManager.GetString("ValueProviderResult_NoConverterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model item passed into the dictionary is null, but this dictionary requires a non-null model item of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ViewDataDictionary_ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ViewDataDictionary_ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model item passed into the dictionary is of type &apos;{0}&apos;, but this dictionary requires a model item of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ViewDataDictionary_WrongTModelType {
            get {
                return ResourceManager.GetString("ViewDataDictionary_WrongTModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A ViewMasterPage can be used only with content pages that derive from ViewPage or ViewPage&lt;TViewItem&gt;. 的本地化字符串。
        /// </summary>
        internal static string ViewMasterPage_RequiresViewPage {
            get {
                return ResourceManager.GetString("ViewMasterPage_RequiresViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution of the child request failed. Please examine the InnerException for more information. 的本地化字符串。
        /// </summary>
        internal static string ViewPageHttpHandlerWrapper_ExceptionOccurred {
            get {
                return ResourceManager.GetString("ViewPageHttpHandlerWrapper_ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ViewUserControl &apos;{0}&apos; cannot find an IViewDataContainer object. The ViewUserControl must be inside a ViewPage, a ViewMasterPage, or another ViewUserControl. 的本地化字符串。
        /// </summary>
        internal static string ViewUserControl_RequiresViewDataProvider {
            get {
                return ResourceManager.GetString("ViewUserControl_RequiresViewDataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A ViewUserControl can be used only in pages that derive from ViewPage or ViewPage&lt;TViewItem&gt;. 的本地化字符串。
        /// </summary>
        internal static string ViewUserControl_RequiresViewPage {
            get {
                return ResourceManager.GetString("ViewUserControl_RequiresViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A master name cannot be specified when the view is a ViewUserControl. 的本地化字符串。
        /// </summary>
        internal static string WebFormViewEngine_UserControlCannotHaveMaster {
            get {
                return ResourceManager.GetString("WebFormViewEngine_UserControlCannotHaveMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The view found at &apos;{0}&apos; was not created. 的本地化字符串。
        /// </summary>
        internal static string WebFormViewEngine_ViewCouldNotBeCreated {
            get {
                return ResourceManager.GetString("WebFormViewEngine_ViewCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The view at &apos;{0}&apos; must derive from ViewPage, ViewPage&lt;TViewData&gt;, ViewUserControl, or ViewUserControl&lt;TViewData&gt;. 的本地化字符串。
        /// </summary>
        internal static string WebFormViewEngine_WrongViewBase {
            get {
                return ResourceManager.GetString("WebFormViewEngine_WrongViewBase", resourceCulture);
            }
        }
    }
}
